### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by chaoswong1981** [RangiLyu/nanodet#147]
我是下载的最新的代码进行的训练，但出现了CUDA内存不足的问题，见下图。
![1png](https://user-images.githubusercontent.com/1501860/107850701-4edc7d80-6e3f-11eb-88da-e6923367bc71.png)

我的训练数据1600多张，是VOC格式的；识别类别只有2类。
使用的GPU是Telsa T4 16G，GPU相关的训练参数是：
```yaml
device:
  gpu_ids: [0]
  workers_per_gpu: 12
  batchsize_per_gpu: 80
```

请各位帮忙看下是啥问题呢？
