### ISSUE TITLE
训练模型的大小和预期不一致

### ISSUE THREAD

**Issue by zhedahe** [RangiLyu/nanodet#312]
大佬好！
我按照如何训练的说明，修改config/nanodet_custom_xml_dataset.yml，训练得到模型的大小为7.7M，推理结果也正确，感谢大佬。我又尝试修改了config/nanodet-m.yml，但是训练出来的模型大小也是7.7M，我看了backbone 是：ShuffleNetV2，这和README文件里的预期：1.8MB(FP16) | 不一致，想请教一下是怎么回事，谢谢！
以下是我的nanodet-m.yml修改内容：

```
#Config File example
save_dir: /home/hzyj/workspace/nanodet/xxx_custom
model:
  arch:
    name: OneStageDetector
    backbone:
      name: ShuffleNetV2
      model_size: 1.0x
      out_stages: [2,3,4]
      activation: LeakyReLU
    fpn:
      name: PAN
      in_channels: [116, 232, 464]
      out_channels: 96
      start_level: 0
      num_outs: 3
    head:
      name: NanoDetHead
      num_classes: 2
      input_channel: 96
      feat_channels: 96
      stacked_convs: 2
      share_cls_reg: True
      octave_base_scale: 5
      scales_per_octave: 1
      strides: [8, 16, 32]
      reg_max: 7
      norm_cfg:
        type: BN
      loss:
        loss_qfl:
          name: QualityFocalLoss
          use_sigmoid: True
          beta: 2.0
          loss_weight: 1.0
        loss_dfl:
          name: DistributionFocalLoss
          loss_weight: 0.25
        loss_bbox:
          name: GIoULoss
          loss_weight: 2.0

class_names: ['corner', 'route_card']
data:
  train:
    name: XMLDataset
    class_names: ['corner', 'route_card']
    img_path: /home/hzyj/workspace/nanodet/xxx_custom/train/img # need to modify
    ann_path: /home/hzyj/workspace/nanodet/xxx_custom/train/ann # need to modify
    input_size: [320,320] #[w,h]
    keep_ratio: True
    pipeline:
      perspective: 0.0
      scale: [0.6, 1.4]
      stretch: [[1, 1], [1, 1]]
      rotation: 0
      shear: 0
      translate: 0.2
      flip: 0.5
      brightness: 0.2
      contrast: [0.6, 1.4]
      saturation: [0.5, 1.2]
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
  val:
    name: XMLDataset
    class_names: ['corner', 'route_card']
    img_path: /home/hzyj/workspace/nanodet/hhm_custom/val/img # need to modify
    ann_path: /home/hzyj/workspace/nanodet/hhm_custom/val/ann # need to modify
    input_size: [320,320] #[w,h]
    keep_ratio: True
    pipeline:
      normalize: [[103.53, 116.28, 123.675], [57.375, 57.12, 58.395]]
device:
  gpu_ids: [0]  # need to modify
  workers_per_gpu: 4 # need to modify
  batchsize_per_gpu: 30 # need to modify
schedule:
#  resume:
#  load_model: YOUR_MODEL_PATH
  optimizer:
    name: SGD
    lr: 0.14
    momentum: 0.9
    weight_decay: 0.0001
  warmup:
    name: linear
    steps: 300
    ratio: 0.1
  total_epochs: 400 # need to modify
  lr_schedule:
    name: MultiStepLR
    milestones: [240,260,275]
    gamma: 0.1
  val_intervals: 10
evaluator:
  name: CocoDetectionEvaluator
  save_key: mAP

log:
  interval: 10
```
