### ISSUE TITLE
Does anyone can help to provide a mobilenetv2 config?

### ISSUE THREAD

**Issue by zacario-li** [RangiLyu/nanodet#6]
Does anyone can help to provide a mobilenetv2 config?

**Comment by zacario-li** [comment]
Is this right?
```
  arch:
    name: GFL
    backbone:
      name: MobileNetV2
      out_stages: [2,4,6]
    fpn:
      name: PAN
      in_channels: [32, 96, 1280]
      out_channels: 96
      start_level: 0
      num_outs: 3
```
